### ISSUE TITLE
Linux build: not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#55]
Reproduced as:

```
root@98cfc5f21f55:/# apt-get upgrade
root@98cfc5f21f55:/# apt-get install -y git curl
root@98cfc5f21f55:/# curl -L https://github.com/metanorma/packed-mn/releases/download/v1.3.2/metanorma-linux-x64 -o metanorma
root@98cfc5f21f55:/# git clone https://github.com/CalConnect/csd-vpoll.git
root@98cfc5f21f55:/# chmod +x metanorma 
root@98cfc5f21f55:/# mv metanorma /usr/bin/
root@98cfc5f21f55:/# cd csd-vpoll/
root@98cfc5f21f55:/csd-vpoll# ls
Gemfile  Makefile  README.adoc  metanorma.yml  reference-docs  sources
root@98cfc5f21f55:/csd-vpoll# metanorma sources/cc-51006.adoc 
Skip extra SassC.load_paths
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.13.1/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/sassc-2.4.0/ext/libsass.so': /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/sassc-2.4.0/ext/libsass.so: cannot open shared object file: No such file or directory. (LoadError)
Could not open library '/tmp/d20200716-3148-kv2o0l/libsass.so': /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/d20200716-3148-kv2o0l/libsass.so)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/ffi-1.13.1/lib/ffi/library.rb:99:in `ffi_lib'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/sassc-2.4.0/lib/sassc/native.rb:13:in `rescue in <module:Native>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/sassc-2.4.0/lib/sassc/native.rb:10:in `<module:Native>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/sassc-2.4.0/lib/sassc/native.rb:6:in `<module:SassC>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/sassc-2.4.0/lib/sassc/native.rb:5:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.1/lib/isodoc/convert.rb:2:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.1/lib/isodoc/convert.rb:2:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.1/lib/isodoc.rb:17:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.1.1/lib/isodoc.rb:17:in `<top (required)>'
	from /__enclose_io_memfs__/local/metanorma:163:in `require'
	from /__enclose_io_memfs__/local/metanorma:163:in `<main>'
```

**Comment by douglm** [comment]
This wasn't the docker container...

**Comment by ronaldtse** [comment]
Ah, I meant that I was doing this within a docker container 😉

**Comment by CAMOBAP** [comment]
According to research, it looks like `libstdc++6` outdated

Step:
 - update gcc to 9 version as described here https://askubuntu.com/a/1149383/108937
 - upgrade libstdc++6 with `apt-get --only-upgrade install libstdc++6`

@w00lf maybe you know, can we 'downgrade' this requirements somehow?

**Comment by CAMOBAP** [comment]
The static link approach should work, one more test in progress

**Comment by CAMOBAP** [comment]
Doesn't work, more information was gathere
 - According to the log, ruby-sassc native extension wasn't recompiled
 - https://github.com/pmq20/ruby-packer/issues/50 - similar issue was reported a while ago
 - There was introduced an option for static linkage libsass, https://github.com/sass/sassc-ruby/commit/82caf8e6e457796a767e59c773db7b301c2210a4

Trying it...

**Comment by w00lf** [comment]
> Doesn't work, more information was gathere
> 
> * According to the log, ruby-sassc native extension wasn't recompiled
> * [pmq20/ruby-packer#50](https://github.com/pmq20/ruby-packer/issues/50) - similar issue was reported a while ago
> * There was introduced an option for static linkage libsass, [sass/sassc-ruby@82caf8e](https://github.com/sass/sassc-ruby/commit/82caf8e6e457796a767e59c773db7b301c2210a4)
> 
> Trying it...

Recently we released new version of isodoc that does not depends on libsass at all an uses precompiled css, let me try to update version and test it.

**Comment by CAMOBAP** [comment]
Original issues fixed,

We have two more sassc related:
 - https://github.com/metanorma/iso-10303/pull/72#issuecomment-663866878
 - https://github.com/metanorma/iso-10303/pull/72#issuecomment-663944574

**Comment by ronaldtse** [comment]
Also, when we test, we should test on both ubuntu 16.04 and ubuntu 18.04.

**Comment by ronaldtse** [comment]
Ping @CAMOBAP this issue still needs fixing, we should add Ubuntu 18.04 into our build matrix.

**Comment by CAMOBAP** [comment]
Works now

**Comment by ronaldtse** [comment]
Thank you!!
